### ISSUE TITLE
Boost Build Fails On FreeBSD

### ISSUE THREAD

**Issue by redsky17** [Nheko-Reborn/mtxclient#1]
The bundled boost library fails to build correctly on FreeBSD because --with-toolchain is not specified with the boost bootstrap.  Update the boost cmake file to specify this parameter (making sure to use the correct one, ie: msvc, gcc, etc)

**Comment by redsky17** [comment]
Fixed in nheko commit bdf6e2b, but I should apply the same updates to the boost build specifically for mtxclient as well.

**Comment by deepbluev7** [comment]
Since this changed a lot, I hope this is either fixed or needs a new fix. Please open a new issue for issues with the new bundled deps!
