### ISSUE TITLE
E2E Key Import / Export Format Does Not Match Spec

### ISSUE THREAD

**Issue by babolivier** [Nheko-Reborn/mtxclient#2]
### System:

- Nheko version: 0.6.3
- Installation method: AppImage
- Operating System: Arch Linux
- Desktop Environment: Gnome Shell (3.30.2)

### Actual behavior

`decrypt_exported_sessions: ciphertext too small` when trying to import E2EE keys from Riot.

### Expected behavior

Keys are imported.

### Steps to reproduce

- Export keys from Riot using the "Export E2E room keys" button
- Import the file in nheko

### Logs

Nothing related in nheko logs.

**Comment by redsky17** [comment]
So the main issue here is that nheko and Riot's key formats are different.  Nheko currently doesn't follow the spec here:
https://matrix.org/docs/spec/client_server/unstable.html#key-export-format

I have been working on this and am nearly finished, but there are still some quirks I'm working out.

**Comment by deepbluev7** [comment]
This is fixed afaik!
