### ISSUE TITLE
Login fails silently if an optional key is missing from /login response

### ISSUE THREAD

**Issue by maxidorius** [Nheko-Reborn/mtxclient#7]
mtxclient will fail to login if the `home_server` key is missing from the [`/login`](https://matrix.org/docs/spec/client_server/r0.4.0.html#post-matrix-client-r0-login) endpoint.

`home_server` is both optional and deprecated so its absence shouldn't lead to any issue.

**Comment by deepbluev7** [comment]
I'm 99% sure, my change just now fixes this. Please reopen, if this is still an issue.
